# configuration variables for tripwire
tripwire:
  user: root
  group: root
  config:
    local_passphrase: 'datanexus'
    site_passphrase: 'datanexus'
    report_dir: /var/lib/tripwire/report
    verbosity: 4
    # write the results to syslog
    syslog: 'true'
  # default_rules: |
 #        /etc/kafka/server.properties        -> $(SEC_CONFIG) ;
 #          /etc/kafka/zookeeper.properties     -> $(SEC_CONFIG) ;
packages:
  epel_version: '7-11'
  # latest available rpm for RHEL6; RHEL7 uses EPEL latest
  tripwire_version: '2.4.3.7-1'
