# configuration variables for tripwire
tripwire:
  user: root
  group: root
  config:
    local_passphrase: 'datanexus'
    site_passphrase: 'datanexus'
    report_dir: /var/lib/tripwire/report
    verbosity: 4
    # write the results to syslog
    syslog: 'true'
  rules: |
        /etc/kafka/server.properties        -> $(SEC_CONFIG) ;
          /etc/kafka/zookeeper.properties     -> $(SEC_CONFIG) ;
