# (c) Copyright 2018 DataNexus Inc.  All Rights Reserved.
#
#
---
- name: TRIPWIRE OVERLAY | checking file integrity (anisble errors can be safely ignored)
  command: 'tripwire --check -L /etc/tripwire/{{ hostvars[inventory_hostname].ansible_hostname }}-local.key'
  become: yes
  register: report
  ignore_errors: yes
  
- debug: msg="{{ report.stdout_lines }}"  
