# (c) Copyright 2018 DataNexus Inc.  All Rights Reserved.
#
#
---
- block:
  
  - block:
    
    - name: TRIPWIRE OVERLAY | installing epel package
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - "epel-release-{{ packages.epel_version }}"
      when: ansible_distribution == 'CentOS' and ansible_distribution_version is version_compare('7', '>=')
    
    - name: TRIPWIRE OVERLAY ({{ ansible_distribution }}) | installing epel package
      yum:
        name: ['https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm']
        state: present
      when: ansible_distribution == 'RedHat' and ansible_distribution_version is version_compare('7', '>=')
      
    # okay to ignore errors here, just means that tripwire isn't present
    - name: TRIPWIRE OVERLAY | locating tripwire binary (fatal errors are acceptable)
      raw: 'which tripwire'
      register: tripwire_binary
      ignore_errors: yes
        
    - name: TRIPWIRE OVERLAY | checking for {{ tripwire_binary.stdout }}
      stat: path={{ tripwire_binary.stdout | trim }}
      register: existing_package

    - block:
      
      - name: TRIPWIRE OVERLAY | fetching tripwire v{{ packages.tripwire_version }}
        get_url:
          url: "https://rpmfind.net/linux/epel/6/x86_64/Packages/t/tripwire-{{ packages.tripwire_version }}.el6.x86_64.rpm"
          dest: "/tmp/tripwire-{{ packages.tripwire_version }}.el6.x86_64.rpm"
          mode: 0640
  
      - name: TRIPWIRE OVERLAY | installing tripwire packages
        package:
          name: "{{ item }}"
          state: present
        with_items:
          - /tmp/tripwire-{{ packages.tripwire_version }}.el6.x86_64.rpm            
      
      when:
        - not existing_package.stat.exists
        - ansible_distribution_version is version_compare('7', '<')
    
    # CentOS / Redhat 7
    - name: TRIPWIRE OVERLAY ({{ ansible_distribution }}) | installing tripwire packages
      package:
        name: ["tripwire-{{ packages.tripwire_version }}.el7"]
        state: present
      when: ansible_distribution_version is version_compare('7', '>=')
  
    when:
      - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  
  - name: TRIPWIRE OVERLAY | checking /etc/tripwire/{{ hostvars[inventory_hostname].ansible_hostname }}-local.key
    stat: path="/etc/tripwire/{{ hostvars[inventory_hostname].ansible_hostname }}-local.key"
    register: existing_key
    
  - name: TRIPWIRE OVERLAY | generating local key (this may take some time)
    command: "twadmin --generate-keys -L /etc/tripwire/{{ hostvars[inventory_hostname].ansible_hostname }}-local.key -P {{ local_passphrase | default(tripwire.config.local_passphrase) }}"
    when: not existing_key.stat.exists
  
  - name: TRIPWIRE OVERLAY | checking /etc/tripwire/site.key
    stat: path=/etc/tripwire/site.key
    register: existing_key
    
  - name: TRIPWIRE OVERLAY | generating site key (this make take some time)
    command: "twadmin --generate-keys -S /etc/tripwire/site.key -Q {{ site_passphrase | default(tripwire.config.site_passphrase) }}"
    when: not existing_key.stat.exists
  
  - name: TRIPWIRE OVERLAY | hacking configuration to enable automation
    lineinfile:
      path: /etc/tripwire/twcfg.txt
      regexp: '^EDITOR'
      line: 'EDITOR                 =/bin/cat'
  
  - name: TRIPWIRE OVERLAY | enabling syslog reporting
    lineinfile:
      path: /etc/tripwire/twcfg.txt
      regexp: '^SYSLOGREPORTING'
      line: "SYSLOGREPORTING        ={{ tripwire.config.syslog }}"
      
  - name: TRIPWIRE OVERLAY | creating and signing configuration file
    command: "twadmin --create-cfgfile -S /etc/tripwire/site.key -Q {{ site_passphrase | default(tripwire.config.site_passphrase) }} /etc/tripwire/twcfg.txt"

  - name: TRIPWIRE OVERLAY | installing {{ ansible_distribution }} tripwire policy into /etc/tripwire
    template:
      src: "twpol-{{ ansible_distribution }}.j2"
      dest: /etc/tripwire/twpol.txt
      mode: 0644
      owner: "{{ tripwire.user }}"
      group: "{{ tripwire.group }}"
  
  - name: TRIPWIRE OVERLAY | ensuring datanexus policy section is present
    blockinfile:
      path: /etc/tripwire/twpol.txt
      insertbefore: "^# disabled-entries:"
      block: |
        # DataNexus platform configuration files.
        (
          rulename = "DataNexus platform configuration",
          severity = $(SIG_HI)
        )
        {
          {{ default_rules | default() }}
          {{ host_rules }}
        }
      marker: "# {{ tenant }} {mark} ANSIBLE MANAGED BLOCK"

  - name: TRIPWIRE OVERLAY | creating and signing policy file
    command: "twadmin --create-polfile -S /etc/tripwire/site.key -Q {{ site_passphrase | default(tripwire.config.site_passphrase) }} /etc/tripwire/twpol.txt" 
  
  - name: TRIPWIRE OVERLAY | creating initial database (this may take some time)
    command: "tripwire --init -L /etc/tripwire/{{ hostvars[inventory_hostname].ansible_hostname }}-local.key -P {{ local_passphrase | default(tripwire.config.local_passphrase) }}"
    
  # - name: TRIPWIRE OVERLAY | checking file integrity (this may take some time)
 #    command: '/sbin/tripwire --check'
    
  become: yes
